=== BackupTheBerlios/visionrobot/antiguo/vision-1_4_05/pipeline.dtd
<?xml version="1.0"?>

<!--
DTD para los archivos descriptores de un pipeline
-->

<!ELEMENT pipeline (modulo+)>
<!ELEMENT modulo (argumento*, modulo*)>
<!ELEMENT argumento (#PCDATA)>
<!ATTLIST modulo ruta CDATA #REQUIRED>
<!ATTLIST argumento tipo CDATA #REQUIRED>

=== BackupTheBerlios/visionrobot/antiguo/vision-1_4_05/nulo.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE pipeline SYSTEM "pipeline.dtd">

<!-- XML ligero para las pruebas -->
<!-- Carlos -->


<pipeline>

  <!-- Generador de imagenes -->
  <modulo ruta="imagenes" nombre="imagenes" inicio="1">
    <argumento nombre="archivo">avanzar.xpm</argumento>
    <argumento nombre="ancho">320</argumento>
    <argumento nombre="alto">240</argumento>
    <argumento nombre="bytes">3</argumento>
    <conexion puerto="salida_imagen">
      <destino puerto="entrada_imagen">ventana</destino>
    </conexion>
  </modulo>

  <!-- Ventana para el filtro de los parametros -->
  <modulo ruta="ventana_imagen" nombre="ventana">
    <argumento nombre="titulo">Ventana</argumento>
    <argumento nombre="nombre_foto">ventana.png</argumento>
    <argumento nombre="extension">png</argumento>
  </modulo>
</pipeline>

=== BackupTheBerlios/visionrobot/antiguo/vision-1_4_05/vision_win.xml
<?xml version="1.0"?>
<!DOCTYPE pipeline SYSTEM "pipeline.dtd">
<pipeline>
  <modulo ruta="camara.dll">
    <argumento tipo="ancho">320</argumento>
    <argumento tipo="alto">240</argumento>
    <argumento tipo="camara">1</argumento>
    <modulo ruta="filtro_gestos.dll">
      <argumento tipo="orden_superior_rojo">230</argumento>
      <argumento tipo="orden_inferior_rojo">5</argumento>
      <argumento tipo="orden_superior_verde">230</argumento>
      <argumento tipo="orden_inferior_verde">5</argumento>
      <argumento tipo="orden_superior_azul">230</argumento>
      <argumento tipo="orden_inferior_azul">2</argumento>
      <argumento tipo="param_superior_rojo">245</argumento>
      <argumento tipo="param_inferior_rojo">20</argumento>
      <argumento tipo="param_superior_verde">240</argumento>
      <argumento tipo="param_inferior_verde">4</argumento>
      <argumento tipo="param_superior_azul">210</argumento>
      <argumento tipo="param_inferior_azul">5</argumento>
      <modulo ruta="ventana_imagen.dll">
	<argumento tipo="nombre_foto">filtro.png</argumento>
	<argumento tipo="extension">png</argumento>
      </modulo>
      
      <modulo ruta="red_neuronal.dll">
	<argumento tipo="archivo">orden.net</argumento>
	<modulo ruta="salida.dll">
	  <argumento tipo="texto">Vision por computador</argumento>
	</modulo>
      </modulo>
    </modulo>
    <modulo ruta="ventana_imagen.dll">
      <argumento tipo="nombre_foto">camara.png</argumento>
      <argumento tipo="extension">png</argumento>
    </modulo>
  </modulo>
  <modulo ruta="imagenes.dll">
    <argumento tipo="ancho">320</argumento>
    <argumento tipo="alto">240</argumento>
    <argumento tipo="bytes">3</argumento>
    <modulo ruta="ventana_imagen.dll">
      <argumento tipo="nombre_foto">imagen.png</argumento>
      <argumento tipo="extension">png</argumento>
    </modulo>
  </modulo>
</pipeline>
