=== BackupTheBerlios/visionrobot/vision/src/libpipeline/pipeline.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!--
DTD para los archivos descriptores de un pipeline
-->

<!ELEMENT pipeline (modulo*)>
<!ELEMENT modulo (argumento*, conexion*)>
<!ELEMENT argumento (#PCDATA)>
<!ELEMENT conexion (destino+)>
<!ELEMENT destino (#PCDATA)>
<!ATTLIST conexion puerto CDATA #REQUIRED>
<!ATTLIST destino puerto CDATA #REQUIRED>                 
<!ATTLIST modulo inicio CDATA "0"
                 ruta CDATA #REQUIRED
                 nombre ID #REQUIRED>
<!ATTLIST argumento nombre CDATA #REQUIRED>

=== BackupTheBerlios/visionrobot/vision/src/camara/camara.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE pipeline SYSTEM "pipeline.dtd">

<!-- XML ligero para las pruebas -->
<!-- Carlos -->


<pipeline>

  <!-- Generador de imagenes -->
    <modulo ruta="camara" nombre="camara" inicio="1">
    <argumento nombre="camara">0</argumento>
    <argumento nombre="ancho">320</argumento>
    <argumento nombre="alto">240</argumento>
    <conexion puerto="salida_imagen">
      <destino puerto="entrada_imagen">ventana</destino>
    </conexion>
  </modulo>
    
  <!-- Ventana para el filtro de los parametros -->
  <modulo ruta="ventana_imagen" nombre="ventana">
    <argumento nombre="titulo">Ventana</argumento>
    <argumento nombre="nombre_foto">ventana.png</argumento>
    <argumento nombre="extension">png</argumento>
  </modulo>
</pipeline>

=== BackupTheBerlios/visionrobot/vision/src/pipeline/vision.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE pipeline SYSTEM "pipeline.dtd">

<pipeline>

  <!-- Ventana de parametros de las ordenes -->
  <modulo ruta="ventana_parametros" nombre="parametros_orden" inicio="1">
    <argumento nombre="rojo">190</argumento>
    <argumento nombre="verde">130</argumento>
    <argumento nombre="azul">120</argumento>
    <argumento nombre="tolerancia_rojo">10</argumento>
    <argumento nombre="tolerancia_verde">10</argumento>
    <argumento nombre="tolerancia_azul">10</argumento>
    <argumento nombre="titulo">Orden</argumento>
    <conexion puerto="salida_filtro">
      <destino puerto="entrada_parametros">filtro_gestos_orden</destino>
    </conexion>
  </modulo>

  <!-- Ventana de parametros de los parametros -->
  <modulo ruta="ventana_parametros" nombre="parametros_param" inicio="1">
    <argumento nombre="rojo">32</argumento>
    <argumento nombre="verde">45</argumento>
    <argumento nombre="azul">123</argumento>
    <argumento nombre="tolerancia_rojo">4</argumento>
    <argumento nombre="tolerancia_verde">6</argumento>
    <argumento nombre="tolerancia_azul">8</argumento>
    <argumento nombre="titulo">Parametro</argumento>
    <conexion puerto="salida_filtro">
      <destino puerto="entrada_parametros">filtro_gestos_param</destino>
    </conexion>
  </modulo>

<!--   Filtro de gestos de las ordenes -->
  <modulo ruta="filtro_gestos" nombre="filtro_gestos_orden">
    <argumento nombre="guion">filtro.lua</argumento>
    <argumento nombre="filtrar">filtrar</argumento>
    <conexion puerto="salida_imagen">
      <destino puerto="entrada_imagen">ventana_filtro_orden</destino>
      <destino puerto="entrada_imagen">red_orden</destino>
    </conexion>
  </modulo>

  <!-- Filtro de gestos de los parametros -->
  <modulo ruta="filtro_gestos" nombre="filtro_gestos_param">
    <argumento nombre="guion">filtro.lua</argumento>
    <argumento nombre="filtrar">filtrar</argumento>
    <conexion puerto="salida_imagen">
      <destino puerto="entrada_imagen">ventana_filtro_param</destino>
      <destino puerto="entrada_imagen">red_param</destino>
    </conexion>
  </modulo>

  <!-- Ventana para el filtro de los parametros -->
  <modulo ruta="ventana_imagen" nombre="ventana_filtro_param">
    <argumento nombre="titulo">Ventana parametros</argumento>
    <argumento nombre="nombre_foto">filtro_param.png</argumento>
    <argumento nombre="extension">png</argumento>
  </modulo>
  
  <!-- Ventana de imagen de las ordenes -->
  <modulo ruta="ventana_imagen" nombre="ventana_filtro_orden">
    <argumento nombre="titulo">Ventana ordenes</argumento>
    <argumento nombre="nombre_foto">filtro_orden.png</argumento>
    <argumento nombre="extension">png</argumento>
  </modulo>

  <!-- Modulo de Prolog (DCG's) -->
  <modulo ruta="prolog" nombre="prolog">
     <conexion puerto="salida_texto">
      <destino puerto="entrada_texto">salida_pipeline</destino>
    </conexion>
  </modulo>

  <!-- Modulo de control de mensajes de la red de ordenes -->
 <modulo ruta="gestion" nombre="gestion_orden">
    <argumento nombre="maximo">3</argumento>
    <argumento nombre="tolerancia">2</argumento>
    <argumento nombre="neutro">no_gesto</argumento>
   <conexion puerto="salida_texto">
      <destino puerto="entrada_orden">post_gestion</destino>
    </conexion>
  </modulo>

  <!-- Modulo de control de mensajes de la red de parametros -->
  <modulo ruta="gestion" nombre="gestion_param">
    <argumento nombre="maximo">7</argumento>
    <argumento nombre="tolerancia">3</argumento>
    <argumento nombre="neutro">no_gesto</argumento>
   <conexion puerto="salida_texto">
      <destino puerto="entrada_param">post_gestion</destino>
    </conexion>
  </modulo>

  <!-- Modulo de post-gestion, se encarga de unir las ordenes con los parametros -->
 <modulo ruta="post_gestion" nombre="post_gestion">
    <argumento nombre="orden_defecto">parar</argumento>
    <argumento nombre="param_defecto">nula</argumento>
    <conexion puerto="salida_robot">
      <destino puerto="entrada_robot">robot</destino>
    </conexion>
    <conexion puerto="salida_texto">
      <destino puerto="entrada_texto">salida_pipeline</destino>
    </conexion>
  </modulo>

  <!--   Filtro de gestos del ocr -->
  <modulo ruta="filtro_gestos" nombre="filtro_gestos_ocr">
    <argumento nombre="guion">filtro.lua</argumento>
    <argumento nombre="filtrar">filtrar_letras</argumento>
    <conexion puerto="salida_imagen">
      <destino puerto="entrada_imagen">ventana_filtro_ocr</destino>
      <destino puerto="entrada_imagen">ocr</destino>
    </conexion>
  </modulo>

  <!-- Ventana de parametros del OCR -->
  <modulo ruta="ventana_parametros" nombre="parametros_ocr" inicio="1">
    <argumento nombre="rojo">247</argumento>
    <argumento nombre="verde">142</argumento>
    <argumento nombre="azul">99</argumento>
    <argumento nombre="tolerancia_rojo">4</argumento>
    <argumento nombre="tolerancia_verde">6</argumento>
    <argumento nombre="tolerancia_azul">8</argumento>
    <argumento nombre="titulo">OCR</argumento>
    <conexion puerto="salida_filtro">
      <destino puerto="entrada_parametros">filtro_gestos_ocr</destino>
    </conexion>
  </modulo>

  <!-- Ventana de imagen del ocr -->
  <modulo ruta="ventana_imagen" nombre="ventana_filtro_ocr">
    <argumento nombre="titulo">Ventana OCR</argumento>
    <argumento nombre="nombre_foto">filtro_ocr.png</argumento>
    <argumento nombre="extension">png</argumento>
  </modulo>

  
  <!-- Generador de imagenes -->
  <modulo ruta="imagenes" nombre="imagenes" inicio="1">
<!--     <argumento nombre="video">robot.mpg</argumento> -->
    <!-- <argumento nombre="camara">1</argumento> -->
    <argumento nombre="archivo">letra.xpm</argumento>
    <argumento nombre="ancho">320</argumento>
    <argumento nombre="alto">240</argumento>
    <argumento nombre="bytes">3</argumento>
    <conexion puerto="salida_imagen">
      <destino puerto="entrada_imagen">filtro_gestos_orden</destino>
      <destino puerto="entrada_imagen">filtro_gestos_param</destino>
      <destino puerto="entrada_imagen">filtro_gestos_ocr</destino>
      <destino puerto="entrada_imagen">ventana_imagenes</destino>
    </conexion>
  </modulo>
  
  <!-- Visor de las imagenes generadas -->
  <modulo ruta="ventana_imagen" nombre="ventana_imagenes">
    <argumento nombre="titulo">Imagenes</argumento>
    <argumento nombre="nombre_foto">imagenes.png</argumento>
    <argumento nombre="extension">png</argumento>
  </modulo>
  
  <!-- Red neuronal de las ordenes -->
  <modulo ruta="red_neuronal" nombre="red_orden">
    <argumento nombre="archivo">orden_net</argumento>
    <argumento nombre="salida1">parar</argumento>
    <argumento nombre="salida2">girar</argumento>
    <argumento nombre="salida3">girar_negativo</argumento>
    <argumento nombre="salida4">avanzar</argumento>
    <argumento nombre="no_gesto">no_gesto</argumento>
    <conexion puerto="salida_texto">
      <destino puerto="entrada_red">gestion_orden</destino>
    </conexion>
  </modulo>
  
  <!-- Red neuronal de los parametros -->
  <modulo ruta="red_neuronal" nombre="red_param">
    <argumento nombre="archivo">orden_net</argumento>
    <argumento nombre="salida1">nula</argumento>
    <argumento nombre="salida2">baja</argumento>
    <argumento nombre="salida3">media</argumento>
    <argumento nombre="salida4">alta</argumento>
    <argumento nombre="no_gesto">no_gesto</argumento>
   <conexion puerto="salida_texto">
        <destino puerto="entrada_red">gestion_param</destino>
    </conexion>
  </modulo>
  
  <!-- Modulo de salida -->
  <modulo ruta="salida" nombre="salida_pipeline">
   <argumento nombre="texto">Vision por computador</argumento>
  </modulo>

  <!-- Modulo del robot -->
  <modulo ruta="robot" nombre="robot">
    <argumento nombre="guion">robot.lua</argumento>
    <argumento nombre="funcion_ciclo">ciclo</argumento>
    <argumento nombre="funcion_fin">fin</argumento>
    <argumento nombre="funcion_iniciar">iniciar</argumento>
    <argumento nombre="puerto">1</argumento>
  </modulo>

  <!-- Modulo de reconocimiento de texto (OCR) -->
  <modulo ruta="ocr" nombre="ocr">
    <argumento nombre="archivo">base_datos</argumento>
    <conexion puerto="salida_texto">
      <destino puerto="entrada_red">gestion_ocr</destino>
    </conexion>
  </modulo>

 <!-- Modulo de control de mensajes de la red de ordenes -->
 <modulo ruta="gestion" nombre="gestion_ocr">
    <argumento nombre="maximo">4</argumento>
    <argumento nombre="tolerancia">3</argumento>
    <argumento nombre="neutro">no_gesto</argumento>
    <conexion puerto="salida_texto">
      <destino puerto="entrada_texto">prolog</destino>
    </conexion>
  </modulo>

</pipeline>
