=== BackupTheBerlios/visionrobot/antiguo/vision_15_02_05/pipeline.dtd
<?xml version="1.0" encoding="UTF-8" ?>

<!--
DTD para los archivos descriptores de un pipeline
-->

<!ELEMENT pipeline (modulo*)>
<!ELEMENT modulo (argumento*, conexion*)>
<!ELEMENT argumento (#PCDATA)>
<!ELEMENT conexion EMPTY>
<!ATTLIST conexion puerto_salida CDATA #REQUIRED
                   puerto_entrada CDATA #REQUIRED
                   destino IDREF #REQUIRED>
<!ATTLIST modulo inicio CDATA "0"
                 ruta CDATA #REQUIRED
                 nombre ID #REQUIRED>
<!ATTLIST argumento nombre CDATA #REQUIRED>

=== BackupTheBerlios/visionrobot/antiguo/vision_15_02_05/vc.xml
<?xml version="1.0"?>
<!DOCTYPE pipeline SYSTEM "pipeline.dtd">
<pipeline>
  <modulo ruta="ventana_parametros" nombre="parametros">
    <argumento tipo="orden_rojo">155</argumento>
    <argumento tipo="orden_verde">140</argumento>
    <argumento tipo="orden_azul">135</argumento>
    <argumento tipo="param_rojo">20</argumento>
    <argumento tipo="param_verde">4</argumento>
    <argumento tipo="param_azul">5</argumento>
    <argumento tipo="orden_tolerancia">0</argumento>
    <argumento tipo="param_tolerancia">0</argumento>
  </modulo>
  <modulo ruta="imagenes" nombre="imagenes">
    <argumento tipo="rojo">32</argumento>
    <argumento tipo="verde">45</argumento>
    <argumento tipo="azul">123</argumento>
    <argumento tipo="ancho">320</argumento>
    <argumento tipo="alto">240</argumento>
    <argumento tipo="bytes">3</argumento>
  </modulo>
  <modulo ruta="ventana_imagen" nombre="ventana_imagenes">
    <argumento tipo="nombre_foto">imagenes.png</argumento>
    <argumento tipo="extension">png</argumento>
  </modulo>
  <modulo ruta="filtro_gestos" nombre="filtro_gestos"></modulo>
  <modulo ruta="ventana_imagen" nombre="ventana_filtro">
    <argumento tipo="nombre_foto">filtro.png</argumento>
    <argumento tipo="extension">png</argumento>
  </modulo>
  <conexion origen="imagenes" destino="ventana_imagenes"/>
  <conexion origen="pipeline" destino="imagenes"/>
  <conexion origen="pipeline" destino="parametros"/>
  <conexion origen="parametros" destino="filtro_gestos"/>
  <conexion origen="imagenes" destino="filtro_gestos"/>
  <conexion origen="filtro_gestos" destino="ventana_filtro"/>
</pipeline>

=== BackupTheBerlios/visionrobot/antiguo/vision_15_02_05/vision.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE pipeline SYSTEM "pipeline.dtd">

<pipeline>
  
  <modulo ruta="ventana_parametros" nombre="parametros" inicio="1">
    <argumento nombre="orden_rojo">32</argumento>
    <argumento nombre="orden_verde">45</argumento>
    <argumento nombre="orden_azul">123</argumento>
    <argumento nombre="param_rojo">20</argumento>
    <argumento nombre="param_verde">4</argumento>
    <argumento nombre="param_azul">5</argumento>
    <argumento nombre="orden_tolerancia">4</argumento>
    <argumento nombre="param_tolerancia">4</argumento>
    <conexion puerto="salida_filtro">
      <destino puerto="entrada_parametros">filtro_gestos</destino>
    </conexion>
  </modulo>

  <modulo ruta="filtro_gestos" nombre="filtro_gestos">
    <conexion puerto="salida_imagen_orden">
      <destino puerto="entrada_imagen">ventana_filtro_orden</destino>
    </conexion>

    <conexion puerto="salida_imagen_param">
      <destino puerto="entrada_imagen">ventana_filtro_param</destino>
    </conexion>

    <!-- <conexion puerto_origen="A" destino="red_neuronal" puerto_destino="entrada_imagen"/> -->
  </modulo>

  <modulo ruta="ventana_imagen" nombre="ventana_filtro_param">
    <argumento nombre="nombre_foto">filtro_param.png</argumento>
    <argumento nombre="extension">png</argumento>
  </modulo>

  <modulo ruta="ventana_imagen" nombre="ventana_filtro_orden">
    <argumento nombre="nombre_foto">filtro_orden.png</argumento>
    <argumento nombre="extension">png</argumento>
  </modulo>

 <modulo ruta="imagenes" nombre="imagenes" inicio="1">
    <argumento nombre="archivo">foto.xpm</argumento>
    <argumento nombre="rojo">32</argumento>
    <argumento nombre="verde">45</argumento>
    <argumento nombre="azul">123</argumento>
    <argumento nombre="ancho">320</argumento>
    <argumento nombre="alto">240</argumento>
    <argumento nombre="bytes">3</argumento>
    <conexion puerto="salida_filtro">
      <destino puerto="entrada_imagen">filtro_gestos</destino>
    </conexion>
    <conexion puerto="salida_ventana">
      <destino puerto="entrada_imagen">ventana_imagenes</destino>
    </conexion>
  </modulo>

  <modulo ruta="ventana_imagen" nombre="ventana_imagenes">
    <argumento nombre="nombre_foto">imagenes.png</argumento>
    <argumento nombre="extension">png</argumento>
  </modulo>


<!--  <modulo ruta="camara" nombre="camara" inicio="1">
    <argumento nombre="ancho">320</argumento>
    <argumento nombre="alto">240</argumento>
    <argumento nombre="camara">0</argumento>
    <conexion puerto_origen="A" destino="filtro_gestos" puerto_destino="A"/>
    <conexion puerto_origen="A" destino="ventana_imagenes" puerto_destino="A"/>
  </modulo>

  <modulo ruta="red_neuronal" nombre="red" inicio="1">
    <argumento nombre="archivo_ordenes">orden_net</argumento> 
    <argumento nombre="archivo_parametros">param_net</argumento> 
    <conexion puerto_origen="salida_texto" destino="filtro_gestos" puerto_destino="entrada_texto"/>
  </modulo> 


  <modulo ruta="salida" nombre="salida">
    <argumento nombre="texto">Vision por computador</argumento>
  </modulo> -->

</pipeline>
